In [0]:
#Colab para o desafio de modelos preditivos:

In [0]:
#importando as bibliotecas
import pandas as pd  #bibioteca responsável para o tratamento e limpeza dos dados
import numpy as np #biblioteca utilizada para o tratamento eficiente de dados numéricos
import datetime  #biblioteca utilizada para trabalhar com datas
from sklearn import datasets
import matplotlib.pyplot as plt

In [0]:
#importando os dados para o google colab
from google.colab import files
uploaded = files.upload()

Saving winequality-red.csv to winequality-red (5).csv


In [0]:
#importando os dados como um dataframe
df_wine=pd.read_csv('winequality-red.csv', sep=';')   #dataset que contém informações sobre diferentes livros existentes na "British Library"

In [0]:
#análise e exploração dos dados

In [0]:
#explorando o dataset 
df_wine.head()

fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0            7.4              0.70         0.00  ...       0.56      9.4        5
1            7.8              0.88         0.00  ...       0.68      9.8        5
2            7.8              0.76         0.04  ...       0.65      9.8        5
3           11.2              0.28         0.56  ...       0.58      9.8        6
4            7.4              0.70         0.00  ...       0.56      9.4        5

[5 rows x 12 columns]

In [0]:
#obtendo informações sobre o dataset
df_wine.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


In [1]:
#média,desvio padrão e mediana
df_wine.describe()

NameError: ignored

In [0]:
#Valores nulos
df_wine.isnull().sum()

In [0]:
#conta os valores para a coluna quality
df_wine['quality'].value_counts() 

In [0]:
# separando dados entrada e saida
x = df_wine.iloc[:, 0:11]
y = df_wine.iloc[:, -1]

In [0]:
print(x)

In [0]:
from sklearn import preprocessing

In [0]:
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
x = pd.DataFrame(x_scaled)

In [0]:
x.describe()

0            1   ...           9            10
count  1599.000000  1599.000000  ...  1599.000000  1599.000000
mean      0.329171     0.279329  ...     0.196496     0.311228
std       0.154079     0.122644  ...     0.101501     0.163949
min       0.000000     0.000000  ...     0.000000     0.000000
25%       0.221239     0.184932  ...     0.131737     0.169231
50%       0.292035     0.273973  ...     0.173653     0.276923
75%       0.407080     0.356164  ...     0.239521     0.415385
max       1.000000     1.000000  ...     1.000000     1.000000

[8 rows x 11 columns]

In [0]:
#separando dados treino e teste
from sklearn.model_selection import train_test_split

In [0]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, stratify=y, random_state=1)

In [0]:
df_wine.head()

In [0]:
#KNN
from sklearn.neighbors import KNeighborsClassifier
clf_KNN = KNeighborsClassifier(n_neighbors=5) 

In [0]:
clf_KNN.fit(x_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [0]:
resultado_knn = clf_KNN.predict(x_test)
resultado_knn

array([6, 5, 6, 5, 5, 6, 5, 6, 6, 5, 5, 7, 5, 6, 7, 5, 6, 5, 6, 5, 6, 6,
       6, 5, 5, 7, 5, 6, 5, 6, 5, 5, 5, 5, 5, 5, 6, 5, 5, 6, 5, 6, 6, 5,
       7, 6, 6, 5, 5, 6, 6, 5, 6, 6, 5, 6, 5, 5, 6, 5, 6, 7, 5, 5, 5, 5,
       5, 5, 6, 6, 5, 6, 5, 5, 5, 5, 5, 5, 6, 6, 7, 5, 5, 6, 7, 6, 7, 7,
       5, 5, 6, 5, 5, 5, 5, 5, 6, 6, 6, 5, 5, 6, 6, 7, 6, 5, 5, 5, 6, 7,
       6, 5, 5, 6, 6, 5, 5, 6, 5, 5, 5, 7, 5, 5, 5, 6, 7, 5, 6, 6, 5, 5,
       5, 6, 5, 5, 5, 5, 5, 6, 6, 5, 5, 6, 5, 6, 6, 5, 6, 6, 6, 6, 6, 6,
       5, 7, 6, 6, 6, 5, 6, 5, 5, 5, 5, 5, 6, 5, 6, 7, 5, 6, 4, 6, 5, 5,
       6, 6, 6, 6, 6, 5, 5, 5, 7, 5, 7, 6, 6, 5, 7, 6, 6, 5, 6, 6, 5, 6,
       5, 5, 5, 7, 6, 6, 5, 6, 6, 6, 7, 5, 6, 5, 6, 6, 5, 5, 5, 5, 6, 5,
       6, 5, 6, 6, 5, 5, 6, 6, 6, 5, 5, 5, 5, 6, 6, 5, 5, 5, 5, 6, 6, 6,
       6, 5, 6, 6, 6, 5, 5, 5, 6, 6, 5, 6, 6, 5, 6, 6, 6, 6, 7, 5, 6, 5,
       5, 5, 5, 6, 6, 7, 6, 7, 6, 6, 6, 6, 5, 7, 5, 6, 6, 6, 5, 5, 7, 5,
       6, 5, 5, 6, 5, 6, 6, 5, 6, 5, 6, 5, 7, 5, 6,

In [0]:
print (pd.crosstab(y_test,resultado_knn, rownames=['Real'], colnames=['Predito'], margins=True))

Predito  4    5    6   7  All
Real                         
3        1    1    1   0    3
4        0   11    5   0   16
5        0  147   54   3  204
6        0   55  122  15  192
7        0   13   27  20   60
8        0    0    3   2    5
All      1  227  212  40  480


In [0]:
from sklearn import metrics
print(metrics.classification_report(y_test,resultado_knn))

              precision    recall  f1-score   support

           3       0.00      0.00      0.00         3
           4       0.00      0.00      0.00        16
           5       0.65      0.72      0.68       204
           6       0.58      0.64      0.60       192
           7       0.50      0.33      0.40        60
           8       0.00      0.00      0.00         5

    accuracy                           0.60       480
   macro avg       0.29      0.28      0.28       480
weighted avg       0.57      0.60      0.58       480



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [0]:
# Floresta Randomica
from sklearn.ensemble import RandomForestClassifier

In [0]:
clf_floresta = RandomForestClassifier(max_depth=10, random_state=1) 

In [0]:
clf_floresta.fit(x_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=10, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=1, verbose=0,
                       warm_start=False)

In [0]:
resultado_floresta = clf_floresta.predict(x_test)
resultado_floresta

array([6, 6, 7, 5, 5, 6, 5, 6, 6, 5, 5, 7, 5, 6, 6, 6, 6, 5, 5, 6, 6, 6,
       6, 6, 5, 6, 5, 6, 5, 6, 5, 6, 5, 5, 5, 5, 6, 5, 5, 6, 6, 5, 6, 5,
       7, 5, 6, 6, 5, 6, 6, 5, 6, 5, 5, 6, 5, 5, 6, 5, 6, 7, 5, 7, 6, 5,
       5, 5, 5, 6, 5, 6, 5, 5, 5, 6, 5, 5, 6, 5, 6, 6, 5, 6, 7, 6, 5, 7,
       5, 5, 5, 6, 5, 5, 5, 5, 6, 6, 6, 5, 5, 6, 6, 6, 6, 5, 5, 5, 6, 6,
       6, 5, 5, 6, 7, 5, 6, 5, 5, 5, 5, 7, 5, 7, 5, 7, 6, 6, 6, 5, 5, 5,
       5, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 5, 6, 5, 6, 6, 6, 6, 6, 6, 6,
       5, 7, 6, 6, 5, 5, 6, 5, 5, 5, 6, 6, 6, 5, 6, 7, 5, 6, 5, 6, 6, 6,
       6, 5, 6, 6, 6, 6, 5, 5, 6, 5, 7, 6, 6, 5, 6, 6, 6, 6, 6, 6, 5, 5,
       5, 5, 5, 7, 6, 6, 5, 6, 6, 5, 6, 5, 5, 5, 5, 6, 5, 6, 5, 5, 6, 5,
       6, 6, 6, 6, 5, 5, 6, 6, 6, 5, 5, 5, 5, 6, 6, 5, 5, 5, 5, 6, 5, 6,
       6, 5, 5, 5, 6, 5, 5, 6, 7, 6, 5, 7, 6, 5, 6, 6, 6, 5, 7, 5, 5, 5,
       5, 5, 5, 5, 6, 6, 7, 7, 6, 7, 6, 6, 6, 6, 5, 5, 6, 6, 5, 5, 7, 5,
       6, 5, 5, 6, 5, 5, 6, 5, 5, 5, 6, 5, 7, 5, 6,

In [0]:
print (pd.crosstab(y_test,resultado_floresta, rownames=['Real'], colnames=['Predito'], margins=True))

Predito    5    6   7  All
Real                      
3          3    0   0    3
4         10    6   0   16
5        171   32   1  204
6         43  141   8  192
7          2   34  24   60
8          0    4   1    5
All      229  217  34  480


In [0]:
print(metrics.classification_report(y_test,resultado_floresta))

              precision    recall  f1-score   support

           3       0.00      0.00      0.00         3
           4       0.00      0.00      0.00        16
           5       0.75      0.84      0.79       204
           6       0.65      0.73      0.69       192
           7       0.71      0.40      0.51        60
           8       0.00      0.00      0.00         5

    accuracy                           0.70       480
   macro avg       0.35      0.33      0.33       480
weighted avg       0.67      0.70      0.68       480



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [0]:
# arvore de decisão
from sklearn.tree import DecisionTreeClassifier


In [0]:
clf_arvore = DecisionTreeClassifier()

In [0]:
clf_arvore.fit(x_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [0]:
resultado_arvore = clf_arvore.predict(x_test)
resultado_arvore

array([5, 7, 7, 6, 5, 6, 5, 6, 6, 5, 5, 7, 5, 6, 6, 6, 5, 6, 5, 3, 6, 7,
       4, 5, 5, 7, 5, 6, 4, 5, 5, 6, 5, 5, 6, 5, 6, 5, 6, 6, 8, 5, 5, 5,
       8, 5, 6, 4, 6, 6, 7, 3, 6, 5, 5, 6, 5, 5, 6, 6, 6, 7, 5, 7, 6, 5,
       6, 6, 6, 5, 5, 6, 5, 5, 6, 5, 6, 6, 4, 5, 6, 6, 5, 4, 7, 6, 5, 7,
       5, 5, 6, 5, 5, 5, 5, 5, 5, 7, 5, 5, 6, 6, 6, 6, 6, 4, 5, 5, 6, 6,
       6, 6, 5, 6, 7, 5, 5, 7, 6, 6, 4, 7, 5, 6, 6, 7, 6, 6, 6, 6, 5, 6,
       5, 7, 5, 5, 5, 5, 4, 5, 5, 6, 6, 6, 5, 6, 5, 6, 6, 6, 6, 6, 8, 6,
       5, 7, 6, 6, 6, 5, 6, 6, 5, 5, 5, 6, 5, 5, 6, 7, 5, 3, 6, 6, 7, 6,
       6, 5, 6, 6, 6, 6, 5, 4, 7, 5, 7, 6, 6, 5, 6, 6, 6, 6, 7, 6, 6, 5,
       6, 6, 5, 6, 6, 6, 6, 6, 6, 5, 6, 4, 4, 5, 6, 6, 5, 6, 4, 5, 6, 5,
       6, 6, 6, 6, 5, 5, 6, 6, 6, 5, 5, 4, 5, 6, 6, 6, 5, 5, 5, 6, 5, 6,
       6, 5, 5, 5, 5, 5, 5, 5, 7, 4, 5, 7, 6, 5, 5, 6, 5, 6, 7, 5, 6, 5,
       5, 5, 4, 5, 5, 6, 7, 7, 5, 7, 5, 6, 6, 6, 6, 5, 6, 6, 5, 5, 7, 5,
       6, 6, 5, 6, 5, 6, 6, 5, 5, 5, 6, 5, 7, 5, 6,

In [0]:
print (pd.crosstab(y_test,resultado_arvore, rownames=['Real'], colnames=['Predito'], margins=True))

Predito  3   4    5    6   7  8  All
Real                                
3        0   0    2    1   0  0    3
4        0   1    7    7   1  0   16
5        1  15  142   39   7  0  204
6        2   6   34  136  12  2  192
7        0   1    2   21  32  4   60
8        0   0    0    3   0  2    5
All      3  23  187  207  52  8  480


In [0]:
print(metrics.classification_report(y_test,resultado_arvore))

              precision    recall  f1-score   support

           3       0.00      0.00      0.00         3
           4       0.04      0.06      0.05        16
           5       0.76      0.70      0.73       204
           6       0.66      0.71      0.68       192
           7       0.62      0.53      0.57        60
           8       0.25      0.40      0.31         5

    accuracy                           0.65       480
   macro avg       0.39      0.40      0.39       480
weighted avg       0.67      0.65      0.66       480



In [0]:
# SVM
from sklearn.svm import SVC

In [0]:
clf_svm=SVC(gamma='auto',kernel='rbf') 

In [0]:
clf_svm.fit(x_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [0]:
resultado_svm = clf_svm.predict(x_test)
resultado_svm

array([6, 6, 6, 5, 5, 6, 5, 5, 6, 5, 5, 6, 6, 6, 6, 5, 5, 5, 5, 5, 6, 6,
       6, 6, 5, 6, 5, 6, 5, 6, 5, 5, 6, 5, 5, 5, 6, 5, 5, 5, 6, 6, 6, 5,
       6, 5, 6, 5, 5, 5, 6, 5, 6, 5, 5, 5, 6, 6, 6, 5, 6, 6, 5, 6, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 5, 6, 6, 5, 6, 6, 6, 6, 6,
       5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 5, 5, 6, 5, 6, 6, 5, 5, 5, 6, 6,
       6, 5, 5, 6, 6, 5, 5, 6, 5, 5, 5, 6, 5, 6, 5, 6, 6, 5, 6, 5, 6, 6,
       5, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6,
       5, 6, 6, 6, 5, 5, 5, 5, 6, 5, 5, 6, 5, 5, 6, 6, 5, 5, 5, 6, 6, 6,
       6, 5, 5, 6, 6, 5, 5, 5, 6, 5, 6, 6, 5, 5, 6, 6, 5, 6, 6, 6, 5, 5,
       5, 5, 5, 6, 6, 6, 5, 6, 6, 5, 6, 5, 5, 5, 5, 6, 5, 5, 5, 5, 6, 5,
       5, 5, 5, 6, 5, 5, 5, 6, 6, 5, 5, 5, 5, 6, 6, 5, 5, 5, 5, 6, 5, 5,
       6, 5, 5, 5, 5, 5, 5, 5, 6, 5, 5, 6, 6, 5, 6, 6, 5, 5, 6, 5, 5, 5,
       5, 5, 5, 5, 5, 6, 5, 6, 5, 6, 5, 6, 6, 6, 5, 6, 6, 6, 5, 5, 6, 5,
       5, 5, 5, 6, 5, 5, 6, 5, 5, 5, 6, 5, 6, 5, 5,

In [0]:
print (pd.crosstab(y_test,resultado_svm, rownames=['Real'], colnames=['Predito'], margins=True))

Predito    5    6  All
Real                  
3          3    0    3
4         12    4   16
5        169   35  204
6         90  102  192
7          3   57   60
8          0    5    5
All      277  203  480


In [0]:
print(metrics.classification_report(y_test,resultado_svm))

              precision    recall  f1-score   support

           3       0.00      0.00      0.00         3
           4       0.00      0.00      0.00        16
           5       0.61      0.83      0.70       204
           6       0.50      0.53      0.52       192
           7       0.00      0.00      0.00        60
           8       0.00      0.00      0.00         5

    accuracy                           0.56       480
   macro avg       0.19      0.23      0.20       480
weighted avg       0.46      0.56      0.51       480



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [0]:
# MLP
from sklearn.neural_network import MLPClassifier

In [0]:
clf_mlp = MLPClassifier( alpha=1e-5, hidden_layer_sizes=(5, 5), random_state=1) 

In [0]:
clf_mlp.fit(x_train, y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(5, 5), learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=200,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=1, shuffle=True, solver='adam',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)

In [0]:
resultado_mlp = clf_mlp.predict(x_test)
resultado_mlp

array([6, 6, 6, 6, 5, 6, 5, 5, 6, 5, 5, 7, 6, 6, 6, 5, 6, 5, 5, 6, 6, 6,
       6, 5, 5, 6, 6, 6, 5, 6, 5, 5, 6, 6, 5, 5, 6, 5, 5, 5, 6, 6, 6, 5,
       7, 5, 6, 6, 5, 6, 6, 5, 5, 5, 6, 5, 6, 6, 6, 5, 6, 6, 5, 6, 6, 5,
       5, 6, 5, 5, 5, 6, 6, 5, 5, 5, 5, 5, 6, 5, 7, 6, 5, 6, 6, 5, 6, 7,
       5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 5, 5, 6, 5, 6, 6, 5, 5, 5, 6, 6,
       6, 5, 5, 6, 6, 5, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6, 7, 5, 6, 5, 6, 6,
       6, 6, 5, 5, 5, 6, 5, 6, 5, 6, 5, 6, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6,
       5, 6, 6, 6, 5, 5, 5, 5, 6, 5, 5, 6, 6, 5, 6, 7, 5, 5, 5, 6, 6, 6,
       6, 5, 5, 6, 6, 5, 5, 5, 6, 5, 6, 6, 5, 5, 7, 7, 5, 6, 6, 5, 5, 5,
       5, 5, 5, 6, 6, 6, 5, 6, 6, 5, 6, 5, 5, 6, 5, 5, 5, 5, 6, 5, 6, 5,
       5, 6, 5, 6, 5, 5, 5, 6, 6, 5, 5, 5, 5, 6, 6, 5, 5, 5, 5, 6, 5, 5,
       6, 5, 5, 5, 5, 5, 5, 6, 6, 6, 5, 6, 6, 5, 6, 6, 5, 5, 7, 5, 5, 5,
       5, 6, 5, 5, 5, 6, 5, 6, 5, 6, 5, 6, 6, 6, 5, 6, 6, 6, 5, 5, 7, 5,
       5, 5, 5, 6, 5, 5, 6, 5, 5, 5, 6, 5, 6, 5, 5,

In [0]:
print (pd.crosstab(y_test,resultado_mlp, rownames=['Real'], colnames=['Predito'], margins=True))

Predito    5    6   7  All
Real                      
3          3    0   0    3
4         12    4   0   16
5        151   53   0  204
6         81  101  10  192
7          3   48   9   60
8          0    2   3    5
All      250  208  22  480


In [0]:
print(metrics.classification_report(y_test,resultado_mlp))

              precision    recall  f1-score   support

           3       0.00      0.00      0.00         3
           4       0.00      0.00      0.00        16
           5       0.60      0.74      0.67       204
           6       0.49      0.53      0.51       192
           7       0.41      0.15      0.22        60
           8       0.00      0.00      0.00         5

    accuracy                           0.54       480
   macro avg       0.25      0.24      0.23       480
weighted avg       0.50      0.54      0.51       480



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [0]:
df_wine['quality'].replace('6', '0')
df_wine['quality'].replace('7', '0')
df_wine['quality'].replace('8', '0')
df_wine['quality'].replace('3', '1')
df_wine['quality'].replace('4', '1')
df_wine['quality'].replace('5', '1')

0       5
1       5
2       5
3       6
4       5
       ..
1594    5
1595    6
1596    6
1597    5
1598    6
Name: quality, Length: 1599, dtype: int64

In [0]:
df_wine.head()

fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0            7.4              0.70         0.00  ...       0.56      9.4        5
1            7.8              0.88         0.00  ...       0.68      9.8        5
2            7.8              0.76         0.04  ...       0.65      9.8        5
3           11.2              0.28         0.56  ...       0.58      9.8        6
4            7.4              0.70         0.00  ...       0.56      9.4        5

[5 rows x 12 columns]

In [0]:
# Floresta Randomica
from sklearn.ensemble import RandomForestClassifier

In [0]:

#importando os dados para o google colab
from google.colab import files
uploaded = files.upload()

Saving winequality-red.csv to winequality-red (8).csv


In [0]:
#importando os dados como um dataframe
df_wine_q=pd.read_csv('winequality-red.csv', sep=';')   #dataset que contém informações sobre diferentes livros existentes na "British Library"




In [0]:
df_wine_q.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   object 
dtypes: float64(11), object(1)
memory usage: 150.0+ KB


In [0]:
df_wine_q.quality = df_wine_q.quality.astype(str)

In [0]:
df_wine_q.head()

fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0            7.4              0.70         0.00  ...       0.56      9.4        0
1            7.8              0.88         0.00  ...       0.68      9.8        0
2            7.8              0.76         0.04  ...       0.65      9.8        0
3           11.2              0.28         0.56  ...       0.58      9.8        1
4            7.4              0.70         0.00  ...       0.56      9.4        0

[5 rows x 12 columns]

In [0]:
df_wine_q.quality.replace('8','1',inplace=True)

In [0]:
df_wine_q.describe()

fixed acidity  volatile acidity  ...    sulphates      alcohol
count    1599.000000       1599.000000  ...  1599.000000  1599.000000
mean        8.319637          0.527821  ...     0.658149    10.422983
std         1.741096          0.179060  ...     0.169507     1.065668
min         4.600000          0.120000  ...     0.330000     8.400000
25%         7.100000          0.390000  ...     0.550000     9.500000
50%         7.900000          0.520000  ...     0.620000    10.200000
75%         9.200000          0.640000  ...     0.730000    11.100000
max        15.900000          1.580000  ...     2.000000    14.900000

[8 rows x 11 columns]

In [0]:
# Floresta Randomica
from sklearn.ensemble import RandomForestClassifier

In [0]:
# separando dados entrada e saida
a = df_wine_q.iloc[:, 0:11]
b = df_wine_q.iloc[:, -1]

In [0]:
min_max_scaler = preprocessing.MinMaxScaler()
a_scaled = min_max_scaler.fit_transform(a)
a = pd.DataFrame(a_scaled)

In [0]:
a_train, a_test, b_train, b_test = train_test_split(a, b, test_size=0.3, stratify=b, random_state=1)

In [0]:
clf_floresta_b = RandomForestClassifier(max_depth=10, random_state=1) 

In [0]:
clf_floresta_b.fit(a_train, b_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=10, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=1, verbose=0,
                       warm_start=False)

In [0]:
resultado_floresta_b = clf_floresta_b.predict(a_test)
resultado_floresta_b

array(['1', '1', '0', '1', '0', '0', '1', '1', '0', '1', '0', '1', '0',
       '0', '1', '0', '1', '0', '1', '0', '1', '1', '0', '0', '0', '1',
       '1', '1', '1', '0', '1', '0', '0', '1', '0', '0', '1', '1', '1',
       '1', '0', '1', '1', '0', '0', '1', '0', '1', '0', '1', '1', '0',
       '1', '0', '1', '1', '1', '0', '1', '0', '0', '1', '0', '0', '0',
       '1', '1', '0', '0', '0', '0', '0', '1', '1', '0', '0', '1', '1',
       '0', '0', '0', '1', '1', '1', '0', '1', '0', '1', '0', '0', '1',
       '1', '1', '0', '1', '0', '0', '1', '0', '1', '0', '1', '1', '1',
       '1', '0', '0', '0', '0', '1', '0', '1', '1', '1', '0', '1', '0',
       '1', '0', '0', '0', '0', '0', '0', '1', '0', '1', '1', '1', '0',
       '1', '0', '0', '1', '1', '1', '1', '1', '0', '0', '1', '0', '1',
       '0', '1', '0', '0', '0', '0', '1', '1', '0', '1', '0', '1', '1',
       '0', '1', '0', '1', '0', '0', '1', '0', '0', '1', '0', '1', '1',
       '1', '1', '0', '1', '0', '1', '0', '0', '0', '1', '1', '1

In [0]:
print(metrics.classification_report(b_test,resultado_floresta_b))

              precision    recall  f1-score   support

           0       0.77      0.74      0.76       223
           1       0.78      0.81      0.80       257

    accuracy                           0.78       480
   macro avg       0.78      0.78      0.78       480
weighted avg       0.78      0.78      0.78       480

